// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// walk_with_jaccard_degree_safe_cpp
IntegerVector walk_with_jaccard_degree_safe_cpp(List adj_list, int start_node, int walk_depth, double eps);
RcppExport SEXP _TopKGraphs_walk_with_jaccard_degree_safe_cpp(SEXP adj_listSEXP, SEXP start_nodeSEXP, SEXP walk_depthSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type adj_list(adj_listSEXP);
    Rcpp::traits::input_parameter< int >::type start_node(start_nodeSEXP);
    Rcpp::traits::input_parameter< int >::type walk_depth(walk_depthSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(walk_with_jaccard_degree_safe_cpp(adj_list, start_node, walk_depth, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TopKGraphs_walk_with_jaccard_degree_safe_cpp", (DL_FUNC) &_TopKGraphs_walk_with_jaccard_degree_safe_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_TopKGraphs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
