# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

walk_with_jaccard_degree_safe_cpp <- function(adj_list, start_node, walk_depth = 20L, eps = 1e-3) {
    .Call(`_TopKGraphs_walk_with_jaccard_degree_safe_cpp`, adj_list, start_node, walk_depth, eps)
}

