# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

walk_with_jaccard_degree_safe_cpp <- function(adj_list, start_node, walk_depth = 20L, n_iter = 50L, eps = 1e-3) {
    .Call(`_TopKGraphs_walk_with_jaccard_degree_safe_cpp`, adj_list, start_node, walk_depth, n_iter, eps)
}

stationary_jaccard_walk_cpp <- function(adj_list, start_node, max_iter = 100L, tol = 1e-8, eps = 1e-3) {
    .Call(`_TopKGraphs_stationary_jaccard_walk_cpp`, adj_list, start_node, max_iter, tol, eps)
}

